---
- hosts: all
  gather_facts: yes
  tasks:
  - name: Checking if Jenkins is running
  command: systemctl status jenkins
  register: status.stdout
  debug: 
  var: status
  - name: Start jenkins on port 8000
  command: systemctl start jenkins
  debug:
  var: status.stdout
